// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfK25ekDzUw9JggQ9YPnpl9HedXCrfkhU',
    appId: '1:547782255873:web:45fcff429ec6b4e54a2700',
    messagingSenderId: '547782255873',
    projectId: 'ifta-tracker-768ce',
    authDomain: 'ifta-tracker-768ce.firebaseapp.com',
    storageBucket: 'ifta-tracker-768ce.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC86exx7VSs7sbV9bV9XPAnai_F0QRm46A',
    appId: '1:547782255873:android:17b9c3d52cf96d4e4a2700',
    messagingSenderId: '547782255873',
    projectId: 'ifta-tracker-768ce',
    storageBucket: 'ifta-tracker-768ce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFpaaza5cZQJFYTJ71eZOIrkQmsbtzBsI',
    appId: '1:547782255873:ios:ca9c0f1d906b333a4a2700',
    messagingSenderId: '547782255873',
    projectId: 'ifta-tracker-768ce',
    storageBucket: 'ifta-tracker-768ce.firebasestorage.app',
    iosBundleId: 'com.example.fuelIftaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFpaaza5cZQJFYTJ71eZOIrkQmsbtzBsI',
    appId: '1:547782255873:ios:ca9c0f1d906b333a4a2700',
    messagingSenderId: '547782255873',
    projectId: 'ifta-tracker-768ce',
    storageBucket: 'ifta-tracker-768ce.firebasestorage.app',
    iosBundleId: 'com.example.fuelIftaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfK25ekDzUw9JggQ9YPnpl9HedXCrfkhU',
    appId: '1:547782255873:web:4d4b1d5fc50ff31c4a2700',
    messagingSenderId: '547782255873',
    projectId: 'ifta-tracker-768ce',
    authDomain: 'ifta-tracker-768ce.firebaseapp.com',
    storageBucket: 'ifta-tracker-768ce.firebasestorage.app',
  );
}
